version: '3.4'

services:
  dotnet-todo-api:
    image: "#{MY_REGISTRY}#/rndad/dotnet-todo-api:#{Build.BuildNumber}#"
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=db;Database=todo_apiDb;User=sa;Password=#{SQL_PASS}#;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "JWT__Secret=Super_Secret_Key"
      - "JWT__ValidIssuer=ValidIssuerNet"
      - "JWT__ValidAudience=ValidAudienceNet"
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure
    networks:
      - default
      - todo-api-network

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - "SA_PASSWORD=#{SQL_PASS}#"
      - "ACCEPT_EULA=Y"
    networks:
      - default
      - todo-api-network

networks:
  todo-api-network:
    external: false