version: '3.4'

services:
  dotnet-todo-api:
    image: ahmadilmanfadilah/dotnet-todo-api:#{Build.BuildId}#
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=todo_apiDb;User=sa;Password=${SQL_PASS};MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "JWT__Secret=Super_Secret_Key"
      - "JWT__ValidIssuer=ValidIssuerNet"
      - "JWT__ValidAudience=ValidAudienceNet"
    ports:
      - "5000:5000"
    restart: on-failure