version: '3.4'

services:
  dotnet-todo-api:
    image: ahmadilmanfadilah/dotnet-todo-api:${BuildId}
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=todo_apiDb;User=sa;Password=${SQL_PASS};MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
    ports:
      - "5000:5000"
    restart: on-failure